spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.69.81.83:3306/db_midas?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: midas
    password: midas
    hikari:
      connection-test-query: select 1 from dual

    cloud:
      gcp:
        storage:
          credentials:
            location: classpath:midas-429814-32b3e9bfbb93.json
      project-id: midas-429814
      bucket: midas-429814-32b3e9bfbb93.json

  mail:
    host: smtp.naver.com
    port: 587
    username: goseum24@naver.com
    password: goseumdochi4
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update