spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.36.95:3306/db_midas?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: midas
    password: midas
    hikari:
      connection-test-query: select 1 from dual

    cloud:
      gcp:
        storage:
          credentials:
            location: classpath:midas-424214-e642912c0adf.json
      project-id: midas-424214
      bucket: sprofile

  mail:
    host: smtp.naver.com
    port: 587
    username: goseum24@naver.com
    password: goseumdochi4
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update